#ifndef CHARACTER_LISTINGS_H
#define CHARACTER_LISTINGS_H

// Unknown character
#define UNKNOWN_CHARACTER '?'

// Border characters
#define NORTH_SOUTH_WALL_CHARACTER '-'
#define EAST_WEST_WALL_CHARACTER '|'
#define CORNER_WALL_CHARACTER '+'
#define GENERAL_WALL_CHARACTER 'B'

// Floor characters
#define ROCK_CHARACTER ' '
#define CORRIDOR_CHARACTER '#'

// Player characters
#define PLAYER_TELEPORT_CHARACTER '*'
#define PLAYER_CHARACTER '@'

// Room characters
#define ROOM_CHARACTER '.'

// Staircase characters
#define STAIRCASE_UP_CHARACTER '<'
#define STAIRCASE_DOWN_CHARACTER '>'

// Monster characters
#define MONSTER_CHARACTER_0 '0'
#define MONSTER_CHARACTER_1 '1'
#define MONSTER_CHARACTER_2 '2'
#define MONSTER_CHARACTER_3 '3'
#define MONSTER_CHARACTER_4 '4'
#define MONSTER_CHARACTER_5 '5'
#define MONSTER_CHARACTER_6 '6'
#define MONSTER_CHARACTER_7 '7'
#define MONSTER_CHARACTER_8 '8'
#define MONSTER_CHARACTER_9 '9'
#define MONSTER_CHARACTER_10 '10'
#define MONSTER_CHARACTER_11 '11'
#define MONSTER_CHARACTER_12 '12'
#define MONSTER_CHARACTER_13 '13'
#define MONSTER_CHARACTER_14 '14'
#define MONSTER_CHARACTER_15 '15'

#define ROCK_HARDNESS_MIN 1
#define ROCK_HARDNESS_MAX 199
#define BORDER_HARDNESS 255
#define ROCK_HARDNESS 100
#define ROOM_HARDNESS 0
#define CORRIDOR_HARDNESS 0
#define PLAYER_HARDNESS 0
#define STAIRCASE_HARDNESS 0
#define MONSTER_HARDNESS 0

#endif
